# kubectl apply -f nori-cuya-05-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: nori-cuya-05-secret
  namespace: nori-cuya-05-namespace
type: Opaque
data:
  DATABASE: bm9zcWw=   # en Base64
  URI: bW9uZ29kYitzcnY6Ly9qdWFuOjEyMzQ1QGNsdXN0ZXIwLnpkbDluLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode